import {Noto_Sans} from "next/font/google";
import "./globals.css";
import HeaderNav from "@/components/HeaderNav/HeaderNav";
import {ClerkProvider} from '@clerk/nextjs'


const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

     <ClerkProvider>

    <html lang="en" suppressHydrationWarning>
      <body
        className={`${notoSans.variable} ${notoSans.variable} antialiased`}
     suppressHydrationWarning   >

        
<main className="min-h-screen  w-full bg-purple-800 relative overflow-hidden">
  <div className="absolute bg-purple-300 rounded-full blur-[278.55px] w-full h-screen top-0"></div>
<HeaderNav />


       {children}
   
</main>

      </body>
    </html>
    </ClerkProvider>
  );
}
